CR and trailing space
zenon-prover/zenon pull request #2
Opened 2021-10-01 21:37 UTC by johnyf

These changes remove trailing ` `, `\r`, and replace literal `\r` characters with the escape sequence `\r`.

2021-10-06 12:04 UTC, damiendoligez requested changes
Just a small suggestion. Otherwise, it looks good.

2021-10-06 12:04 UTC, damiendoligez commented on test/Makefile
> +	    echo $$'\r' | tr -d '\n'; \
In modern Unix, I'd write it like this:
```suggestion
	    printf '\r'; \
```

2021-10-06 12:04 UTC, damiendoligez commented on test/Makefile
> +	    echo $$'\r' | tr -d '\n'; \
```suggestion
	    printf '\r'; \
```

2021-10-07 06:12 UTC, johnyf commented on test/Makefile
> +	    echo $$'\r' | tr -d '\n'; \
Thank you for suggesting these changes, I will rebase to update these lines.

2021-10-07 06:20 UTC, johnyf commented
Thank you for reviewing these changes, and suggesting changes, I applied the suggestions and rebased the branch.

2021-10-12 13:16 UTC, damiendoligez approved these changes

2021-10-12 13:17 UTC, merged

2021-10-12 13:17 UTC, damiendoligez commented
Thanks for the PR.

2021-10-12 13:50 UTC, johnyf commented
Thank you for approving and merging these changes.